services:
  scrabble:
    build: .
    container_name: scrabble
    ports:
      - "8031:8080"
    volumes:
      - /Users/jarvis/docker/scrabble/boards:/app/boards
    restart: unless-stopped
    networks:
      - jarvis

networks:
  jarvis:
    external: true
    name: jarvis_default
